<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.6"/>
        <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.6" PrivateAssets="all"/>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Shared\Shared.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="wwwroot\lib\**\*.*">
            <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
        </Content>
        <Content Update="wwwroot\appsettings.Development.json">
          <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

    <Target Name="CopyBootstrapFromNode" BeforeTargets="Build">
        <!-- Cleaning -->
        <RemoveDir Directories="wwwroot\lib"/>
        <MakeDir Directories="wwwroot\lib\bootstrap\css"/>
        <MakeDir Directories="wwwroot\lib\bootstrap\js"/>
        <MakeDir Directories="wwwroot\lib\bootstrap-icons\font\fonts"/>

        <!-- Bootstrap CSS & JS bundle -->
        <Copy SourceFiles="node_modules\bootstrap\dist\css\bootstrap.min.css"
              DestinationFiles="wwwroot\lib\bootstrap\css\bootstrap.min.css"/>
        <Copy SourceFiles="node_modules\bootstrap\dist\js\bootstrap.bundle.min.js"
              DestinationFiles="wwwroot\lib\bootstrap\js\bootstrap.bundle.min.js"/>

        <!-- Bootstrap Icons: CSS + fonts -->
        <Copy SourceFiles="node_modules\bootstrap-icons\font\fonts\bootstrap-icons.woff2"
              DestinationFiles="wwwroot\lib\bootstrap-icons\font\fonts\bootstrap-icons.woff2"/>
        <Copy SourceFiles="node_modules\bootstrap-icons\font\fonts\bootstrap-icons.woff"
              DestinationFiles="wwwroot\lib\bootstrap-icons\font\fonts\bootstrap-icons.woff" Condition="Exists('node_modules\bootstrap-icons\font\fonts\bootstrap-icons.woff')"/>
        <Copy SourceFiles="node_modules\bootstrap-icons\font\bootstrap-icons.css"
              DestinationFiles="wwwroot\lib\bootstrap-icons\font\bootstrap-icons.css"/>
    </Target>

</Project>