using Riok.Mapperly.Abstractions;
using Shared.SRealty.Advert;

namespace Server.Features.SRealty.Advert.Entity;

/// <summary>
/// Mapping between the DTO and the entity, generated by Mapperly at compile time.
/// RequiredMappingStrategy.Target reports any target property left unmapped as RMG012, so together with
/// warnings-as-errors a newly added field breaks the build instead of being dropped in silence.
/// ThrowOnPropertyMappingNullMismatch makes a null in a required field throw, which means only an already
/// validated DTO may be passed in: the mapper is not a substitute for validation.
/// </summary>
[Mapper(
    RequiredMappingStrategy = RequiredMappingStrategy.Target,
    ThrowOnPropertyMappingNullMismatch = true)]
public static partial class SrealityAdvertMapper
{
    // --- DTO -> a new entity (create) ---
    // The caller passes the required portal fields as parameters and Mapperly matches them by name
    // (realtyAgencyId -> RealtyAgencyId, expiresAt -> ExpiresAt).
    // The handler fills in the remaining portal fields and the navigations, so those are ignored here.

    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Id))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.CreatedAt))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.UpdatedAt))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Agency))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Seller))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Photos))] // photos have their own upload endpoint
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityMunicipalityCode))] // placed in the register by the service
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityMunicipality))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityDistrictCode))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityDistrict))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.SearchVector))]
    [MapperIgnoreSource(nameof(SrealityAdvertDto.AdvertId))] // the internal identifier is assigned by the portal
    public static partial SrealityAdvertEntity ToEntity(
        this SrealityAdvertDto dto, Guid? realtyAgencyId, DateTimeOffset expiresAt);

    // --- DTO -> an existing entity (idempotent re-import or update) ---
    // Full replace: a field missing from the DTO is overwritten with null, which is the agreed import behaviour.

    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Id))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.RealtyAgencyId))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.ExpiresAt))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.CreatedAt))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.UpdatedAt))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Agency))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Seller))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.Photos))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityMunicipalityCode))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityMunicipality))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityDistrictCode))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.LocalityDistrict))]
    [MapperIgnoreTarget(nameof(SrealityAdvertEntity.SearchVector))]
    [MapperIgnoreSource(nameof(SrealityAdvertDto.AdvertId))]
    public static partial void UpdateEntity(this SrealityAdvertDto dto, SrealityAdvertEntity entity);

    // --- entity -> DTO (detail responses and the edit form) ---

    [MapProperty(nameof(SrealityAdvertEntity.Id), nameof(SrealityAdvertDto.AdvertId))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.RealtyAgencyId))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.ExpiresAt))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.CreatedAt))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.UpdatedAt))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.Agency))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.Seller))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.Photos))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.LocalityMunicipalityCode))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.LocalityMunicipality))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.LocalityDistrictCode))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.LocalityDistrict))]
    [MapperIgnoreSource(nameof(SrealityAdvertEntity.SearchVector))]
    public static partial SrealityAdvertDto ToDto(this SrealityAdvertEntity entity);

    // --- price conversion: double in the DTO <-> decimal in the database ---
    // Mapperly finds these by their signature and applies them on its own.

    private static decimal ToDecimal(double value) => (decimal)value;
    private static double ToDouble(decimal value) => (double)value;
}
