using NpgsqlTypes;
using Server.Features.RealtyAgency;
using Server.Features.RealtyAgency.Entity;
using Server.Features.RealtyAgent;
using Server.Features.RealtyAgent.Entity;
using Server.Features.Ruian.Entity;
using Server.Features.SRealty.Photo;
using Server.Features.SRealty.Photo.Entity;
using Server.Infrastructure.Database;

namespace Server.Features.SRealty.Advert.Entity;

/// <summary>
/// An advert in the Sreality shape, mirroring SrealityAdvertDto field for field across partial files; this one
/// holds the portal-maintained fields and navigation properties. Agency-supplied fields are nullable.
/// </summary>
public partial class SrealityAdvertEntity: ITimeStampedEntity
{
    public Guid Id { get; set; } = Guid.CreateVersion7();

    /// <summary>Agency the advert is published under; null while its agent has no agency.</summary>
    public Guid? RealtyAgencyId { get; set; }
    public RealtyAgencyEntity? Agency { get; set; }

    /// <summary>Foreign key of the portal agent; null when the agent is identified only by SellerRkId.</summary>
    public Guid? SellerId { get; set; }
    public RealtyAgentEntity? Seller { get; set; }

    /// <summary>Derived from AdvertLifetime when the advert is stored.</summary>
    public required DateTimeOffset ExpiresAt { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>RUIAN municipality resolved from LocalityRuian or LocalityCity; null when neither matched.</summary>
    public int? LocalityMunicipalityCode { get; set; }
    public RuianMunicipalityEntity? LocalityMunicipality { get; set; }

    /// <summary>District of <see cref="LocalityMunicipality"/>, or the one a district-level code names.</summary>
    public int? LocalityDistrictCode { get; set; }
    public RuianDistrictEntity? LocalityDistrict { get; set; }

    /// <summary>
    /// Full-text search words of the description and address, generated by PostgreSQL; absent on other providers.
    /// </summary>
    public NpgsqlTsVector? SearchVector { get; set; }

    public List<SrealityAdvertPhotoEntity> Photos { get; set; } = [];

    /// <summary>Whether the agent may change this advert: published under their agency, or sold by them.</summary>
    public bool IsOwnedBy(RealtyAgentEntity agent)
        => (RealtyAgencyId is not null && RealtyAgencyId == agent.RealtyAgencyId)
           || (SellerId is not null && SellerId == agent.UserId);
}
