using Riok.Mapperly.Abstractions;
using Server.Features.RealtyAgency.Entity;
using Shared.RealtyAgency;

namespace Server.Features.RealtyAgency;

/// <summary>
/// Mapping between the agency DTO and the entity, generated by Mapperly at compile time. Only a validated DTO
/// may be passed in: a null in a required field throws rather than mapping.
/// </summary>
[Mapper(
    RequiredMappingStrategy = RequiredMappingStrategy.Target,
    ThrowOnPropertyMappingNullMismatch = true)]
public static partial class RealtyAgencyMapper
{
    // --- DTO -> a new entity (create); the portal assigns the identifier and the service derives the search name ---

    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.Id))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.CreatedAt))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.UpdatedAt))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.SearchName))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.Agents))]
    [MapperIgnoreSource(nameof(RealtyAgencyDto.Id))]
    public static partial RealtyAgencyEntity ToEntity(this RealtyAgencyDto dto);

    // --- DTO -> an existing entity (update) ---

    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.Id))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.CreatedAt))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.UpdatedAt))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.SearchName))]
    [MapperIgnoreTarget(nameof(RealtyAgencyEntity.Agents))]
    [MapperIgnoreSource(nameof(RealtyAgencyDto.Id))]
    public static partial void UpdateEntity(this RealtyAgencyDto dto, RealtyAgencyEntity entity);

    // --- entity -> DTO ---

    [MapperIgnoreSource(nameof(RealtyAgencyEntity.CreatedAt))]
    [MapperIgnoreSource(nameof(RealtyAgencyEntity.UpdatedAt))]
    [MapperIgnoreSource(nameof(RealtyAgencyEntity.SearchName))]
    [MapperIgnoreSource(nameof(RealtyAgencyEntity.Agents))]
    public static partial RealtyAgencyDto ToDto(this RealtyAgencyEntity entity);
}
