using Riok.Mapperly.Abstractions;
using Server.Features.RealtyAgent.Entity;
using Shared.RealtyAgent;

namespace Server.Features.RealtyAgent;

/// <summary>Mapping between the agent DTO and the entity, generated by Mapperly at compile time.</summary>
[Mapper(
    RequiredMappingStrategy = RequiredMappingStrategy.Target,
    ThrowOnPropertyMappingNullMismatch = true)]
public static partial class RealtyAgentMapper
{
    // --- entity -> DTO ---

    [MapperIgnoreSource(nameof(RealtyAgentEntity.User))]
    [MapperIgnoreSource(nameof(RealtyAgentEntity.RealtyAgency))]
    [MapperIgnoreSource(nameof(RealtyAgentEntity.SRealtyProperties))]
    public static partial RealtyAgentDto ToDto(this RealtyAgentEntity entity);

    // --- DTO -> an existing entity (update) ---
    // Only the role and the agency key move through an update: who the agent is and which agency they work for
    // have their own flows (create, join, leave), so those fields are ignored here.

    [MapperIgnoreTarget(nameof(RealtyAgentEntity.UserId))]
    [MapperIgnoreTarget(nameof(RealtyAgentEntity.User))]
    [MapperIgnoreTarget(nameof(RealtyAgentEntity.RealtyAgencyId))]
    [MapperIgnoreTarget(nameof(RealtyAgentEntity.RealtyAgency))]
    [MapperIgnoreTarget(nameof(RealtyAgentEntity.SRealtyProperties))]
    [MapperIgnoreSource(nameof(RealtyAgentDto.UserId))]
    [MapperIgnoreSource(nameof(RealtyAgentDto.RealtyAgencyId))]
    public static partial void UpdateEntity(this RealtyAgentDto dto, RealtyAgentEntity entity);
}
