<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <WarningsAsErrors>$(WarningsAsErrors);RMG012;RMG020</WarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Aspire.StackExchange.Redis.DistributedCaching" />
        <PackageReference Include="Aspire.StackExchange.Redis.OutputCaching" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
        <PackageReference Include="Microsoft.Extensions.Caching.Hybrid" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL.NetTopologySuite" />
        <PackageReference Include="Riok.Mapperly" />
        <PackageReference Include="Scalar.AspNetCore" />
        <PackageReference Include="Swashbuckle.AspNetCore" />
        <PackageReference Include="Aspire.Npgsql.EntityFrameworkCore.PostgreSQL" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\realty-portal.ServiceDefaults\realty-portal.ServiceDefaults.csproj" />
        <ProjectReference Include="..\Shared\Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <EmbeddedResource Include="Features\Ruian\Data\*.csv" />
      <Folder Include="Features\" />
      <Folder Include="Features\RealtyAgency\CreateRealtyAgency\" />
      <Folder Include="Features\RealtyAgency\DeleteRealtyAgency\" />
      <Folder Include="Features\RealtyAgency\GetRealtyAgencies\" />
      <Folder Include="Features\RealtyAgency\GetRealtyAgency\" />
      <Folder Include="Features\RealtyAgency\UpdateRealtyAgency\" />
      <Folder Include="Features\RealtyAgent\CreateRealtyAgent\" />
      <Folder Include="Features\RealtyAgent\DeleteRealtyAgent\" />
      <Folder Include="Features\RealtyAgent\GetRealtyAgent\" />
      <Folder Include="Features\RealtyAgent\UpdateRealtyAgent\" />
      <Folder Include="Infrastructure\DependencyInjection\" />
    </ItemGroup>
</Project>
