namespace Shared.SRealty.Advert.CreateAdvert;

public enum CreateAdvertResponseStatusEnum
{
    OK = 200,
    OK_RUIAN_CANT_BE_FOUND = 202,
    OK_ADDRESS_AMBIGUOUS = 203,
    OK_INCOMPLETE_DATA = 204,
    OK_NO_PRECISE_ADDRESS = 205,
    INEXISTENT_ADVERT = 404,
    INVALID_LOGIN = 407,
    INCOMPLETE_ADVERT_DATA = 452,
    INVALID_ADVERT_TEXT = 455,
    NONEXISTENT_AGENT = 461,
    UNMODIFIABLE_MAIN_FIELDS = 484,
    INEXISTENT_PROJECT = 491
}