// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Server.Database;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250929185322_Init3")]
    partial class Init3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Server.Entities.RealtyAgency.RealtyAgencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxNumber")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("RealtyAgencies");
                });

            modelBuilder.Entity("Server.Entities.SRealtyRealty.SRealtyPropertyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AdvertFunction")
                        .HasColumnType("integer");

                    b.Property<int>("AdvertLifetime")
                        .HasColumnType("integer");

                    b.Property<double>("AdvertPrice")
                        .HasColumnType("double precision");

                    b.Property<int>("AdvertPriceCurrency")
                        .HasColumnType("integer");

                    b.Property<int>("AdvertPriceUnit")
                        .HasColumnType("integer");

                    b.Property<string>("AdvertRkId")
                        .HasColumnType("text");

                    b.Property<int>("AdvertSubtype")
                        .HasColumnType("integer");

                    b.Property<int>("AdvertType")
                        .HasColumnType("integer");

                    b.Property<double?>("Altitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("Balcony")
                        .HasColumnType("boolean");

                    b.Property<int?>("BalconyArea")
                        .HasColumnType("integer");

                    b.Property<bool>("Basin")
                        .HasColumnType("boolean");

                    b.Property<int?>("BasinArea")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingCondition")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<bool>("Cellar")
                        .HasColumnType("boolean");

                    b.Property<int?>("CellarArea")
                        .HasColumnType("integer");

                    b.Property<int?>("CircuitBreaker")
                        .HasColumnType("integer");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CityPart")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("Electricity")
                        .HasColumnType("integer[]");

                    b.Property<int?>("Elevator")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyEfficiencyCertificate")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyEfficiencyRating")
                        .HasColumnType("integer");

                    b.Property<double?>("EnergyPerformanceSummary")
                        .HasColumnType("double precision");

                    b.Property<int?>("EstateArea")
                        .HasColumnType("integer");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<bool>("FtvPanels")
                        .HasColumnType("boolean");

                    b.Property<int?>("Furnished")
                        .HasColumnType("integer");

                    b.Property<bool>("Garage")
                        .HasColumnType("boolean");

                    b.Property<int?>("GarageArea")
                        .HasColumnType("integer");

                    b.Property<int?>("GarageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("GardenArea")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Gas")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Gully")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Heating")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("HeatingElement")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("HeatingSource")
                        .HasColumnType("integer[]");

                    b.Property<string>("HouseNumber")
                        .HasColumnType("text");

                    b.Property<int>("InaccuracyLevel")
                        .HasColumnType("integer");

                    b.Property<string>("InternetConnectionProvider")
                        .HasColumnType("text");

                    b.Property<int?>("InternetConnectionSpeed")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("InternetConnectionType")
                        .HasColumnType("integer[]");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision");

                    b.Property<bool>("Loggia")
                        .HasColumnType("boolean");

                    b.Property<int?>("LoggiaArea")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<string>("OrientationNumber")
                        .HasColumnType("text");

                    b.Property<int?>("ParkingCount")
                        .HasColumnType("integer");

                    b.Property<bool>("ParkingLots")
                        .HasColumnType("boolean");

                    b.Property<int?>("PhaseDistribution")
                        .HasColumnType("integer");

                    b.Property<string>("PropertyDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("RealtyAgentEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("RealtyAgentId")
                        .HasColumnType("text");

                    b.Property<Guid?>("RealtyAgentRkId")
                        .HasColumnType("uuid");

                    b.Property<int?>("RuianId")
                        .HasColumnType("integer");

                    b.Property<int?>("RuianLevel")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .HasColumnType("text");

                    b.PrimitiveCollection<int[]>("Telecommunication")
                        .HasColumnType("integer[]");

                    b.Property<bool>("Terrace")
                        .HasColumnType("boolean");

                    b.Property<int?>("TerraceArea")
                        .HasColumnType("integer");

                    b.Property<int?>("UirId")
                        .HasColumnType("integer");

                    b.Property<int?>("UirLevel")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsableArea")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Water")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("WaterHeatingSource")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("WellType")
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.HasIndex("RealtyAgentEntityId");

                    b.ToTable("SRealityProperties");
                });

            modelBuilder.Entity("Server.Entities.Users.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Server.Entities.Users.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("RealtyAgencyEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("RealtyAgencyEntityId");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasDiscriminator().HasValue("ApplicationUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Server.Entities.Users.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Server.Entities.Users.Realty.RealtyAgentEntity", b =>
                {
                    b.HasBaseType("Server.Entities.Users.ApplicationUser");

                    b.Property<Guid>("RealtyAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RealtyAgentRkId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasIndex("RealtyAgencyId");

                    b.HasDiscriminator().HasValue("RealtyAgentEntity");
                });

            modelBuilder.Entity("Server.Entities.Users.Realty.RealtyAgencyAdminEntity", b =>
                {
                    b.HasBaseType("Server.Entities.Users.Realty.RealtyAgentEntity");

                    b.HasDiscriminator().HasValue("RealtyAgencyAdminEntity");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Server.Entities.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Server.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Server.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Server.Entities.Users.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Server.Entities.Users.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Entities.SRealtyRealty.SRealtyPropertyEntity", b =>
                {
                    b.HasOne("Server.Entities.Users.Realty.RealtyAgentEntity", null)
                        .WithMany("SRealtyProperties")
                        .HasForeignKey("RealtyAgentEntityId");
                });

            modelBuilder.Entity("Server.Entities.Users.ApplicationUser", b =>
                {
                    b.HasOne("Server.Entities.RealtyAgency.RealtyAgencyEntity", null)
                        .WithMany("RealtyAgent")
                        .HasForeignKey("RealtyAgencyEntityId");
                });

            modelBuilder.Entity("Server.Entities.Users.RefreshTokenEntity", b =>
                {
                    b.HasOne("Server.Entities.Users.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Entities.Users.Realty.RealtyAgentEntity", b =>
                {
                    b.HasOne("Server.Entities.RealtyAgency.RealtyAgencyEntity", "RealtyAgency")
                        .WithMany()
                        .HasForeignKey("RealtyAgencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealtyAgency");
                });

            modelBuilder.Entity("Server.Entities.RealtyAgency.RealtyAgencyEntity", b =>
                {
                    b.Navigation("RealtyAgent");
                });

            modelBuilder.Entity("Server.Entities.Users.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("Server.Entities.Users.Realty.RealtyAgentEntity", b =>
                {
                    b.Navigation("SRealtyProperties");
                });
#pragma warning restore 612, 618
        }
    }
}
