// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using Server.Infrastructure.Database;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Server.Features.RealtyAgency.Entity.RealtyAgencyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("RealtyAgencies");
                });

            modelBuilder.Entity("Server.Features.RealtyAgent.Entity.RealtyAgentEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("AgentRole")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RealtyAgencyId")
                        .HasColumnType("uuid");

                    b.Property<string>("RealtyAgentRkId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("UserId");

                    b.HasIndex("RealtyAgencyId", "RealtyAgentRkId")
                        .IsUnique()
                        .HasFilter("\"RealtyAgentRkId\" IS NOT NULL");

                    b.ToTable("RealtyAgents");
                });

            modelBuilder.Entity("Server.Features.Ruian.Entity.RuianDistrictEntity", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RegionCode")
                        .HasColumnType("integer");

                    b.HasKey("Code");

                    b.HasIndex("RegionCode");

                    b.ToTable("RuianDistricts");
                });

            modelBuilder.Entity("Server.Features.Ruian.Entity.RuianMunicipalityEntity", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<int>("DistrictCode")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.HasIndex("DistrictCode");

                    b.HasIndex("SearchName");

                    b.ToTable("RuianMunicipalities");
                });

            modelBuilder.Entity("Server.Features.Ruian.Entity.RuianRegionEntity", b =>
                {
                    b.Property<int>("Code")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Code");

                    b.ToTable("RuianRegions");
                });

            modelBuilder.Entity("Server.Features.SRealty.Advert.Entity.SrealityAdvertEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int?>("AcceptanceYear")
                        .HasColumnType("integer");

                    b.Property<string>("AdvertCode")
                        .HasColumnType("text");

                    b.Property<int>("AdvertFunction")
                        .HasColumnType("integer");

                    b.Property<int>("AdvertLifetime")
                        .HasColumnType("integer");

                    b.Property<bool>("AdvertLowEnergy")
                        .HasColumnType("boolean");

                    b.Property<decimal>("AdvertPrice")
                        .HasColumnType("numeric(14,2)");

                    b.Property<int>("AdvertPriceCurrency")
                        .HasColumnType("integer");

                    b.Property<bool>("AdvertPriceNegotiation")
                        .HasColumnType("boolean");

                    b.Property<string>("AdvertPriceTextNote")
                        .HasColumnType("text");

                    b.Property<string>("AdvertPriceTextNoteEn")
                        .HasColumnType("text");

                    b.Property<string>("AdvertPriceTextNoteRu")
                        .HasColumnType("text");

                    b.Property<int>("AdvertPriceUnit")
                        .HasColumnType("integer");

                    b.Property<string>("AdvertRkId")
                        .HasColumnType("text");

                    b.Property<int?>("AdvertRoomCount")
                        .HasColumnType("integer");

                    b.Property<int>("AdvertSubtype")
                        .HasColumnType("integer");

                    b.Property<int>("AdvertType")
                        .HasColumnType("integer");

                    b.Property<int?>("Annuity")
                        .HasColumnType("integer");

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("AuctionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AuctionDateTour")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AuctionDateTour2")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AuctionKind")
                        .HasColumnType("integer");

                    b.Property<string>("AuctionPlace")
                        .HasColumnType("text");

                    b.Property<bool>("Balcony")
                        .HasColumnType("boolean");

                    b.Property<int?>("BalconyArea")
                        .HasColumnType("integer");

                    b.Property<bool>("Basin")
                        .HasColumnType("boolean");

                    b.Property<int?>("BasinArea")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("BeginningDate")
                        .HasColumnType("date");

                    b.Property<int?>("Bidding")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingArea")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingCondition")
                        .HasColumnType("integer");

                    b.Property<int?>("BuildingType")
                        .HasColumnType("integer");

                    b.Property<double?>("CeilingHeight")
                        .HasColumnType("double precision");

                    b.Property<bool>("Cellar")
                        .HasColumnType("boolean");

                    b.Property<int?>("CellarArea")
                        .HasColumnType("integer");

                    b.Property<int?>("CircuitBreaker")
                        .HasColumnType("integer");

                    b.Property<double?>("Commission")
                        .HasColumnType("double precision");

                    b.Property<string>("CostOfLiving")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionEn")
                        .HasColumnType("text");

                    b.Property<string>("DescriptionRu")
                        .HasColumnType("text");

                    b.Property<int?>("EasyAccess")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Electricity")
                        .HasColumnType("integer[]");

                    b.Property<int?>("Elevator")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyEfficiencyRating")
                        .HasColumnType("integer");

                    b.Property<int?>("EnergyPerformanceCertificate")
                        .HasColumnType("integer");

                    b.Property<double?>("EnergyPerformanceSummary")
                        .HasColumnType("double precision");

                    b.Property<int?>("EstateArea")
                        .HasColumnType("integer");

                    b.Property<bool>("ExclusivelyAtRk")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExtraInfo")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("FinishDate")
                        .HasColumnType("date");

                    b.Property<DateTimeOffset?>("FirstTourDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("FirstTourDateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FlatClass")
                        .HasColumnType("integer");

                    b.Property<int?>("FloorArea")
                        .HasColumnType("integer");

                    b.Property<int?>("FloorNumber")
                        .HasColumnType("integer");

                    b.Property<int?>("Floors")
                        .HasColumnType("integer");

                    b.Property<bool>("FtvPanels")
                        .HasColumnType("boolean");

                    b.Property<int?>("Furnished")
                        .HasColumnType("integer");

                    b.Property<bool>("Garage")
                        .HasColumnType("boolean");

                    b.Property<int?>("GarageCount")
                        .HasColumnType("integer");

                    b.Property<int?>("GardenArea")
                        .HasColumnType("integer");

                    b.Property<bool>("Garret")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("Gas")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Gully")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("Heating")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("HeatingElement")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("HeatingSource")
                        .HasColumnType("integer[]");

                    b.Property<string>("InternetConnectionProvider")
                        .HasColumnType("text");

                    b.Property<int?>("InternetConnectionSpeed")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("InternetConnectionType")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<List<string>>("Keywords")
                        .HasColumnType("text[]");

                    b.Property<int?>("LeaseType")
                        .HasColumnType("integer");

                    b.Property<string>("LocalityCity")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LocalityCityPart")
                        .HasColumnType("text");

                    b.Property<string>("LocalityCo")
                        .HasColumnType("text");

                    b.Property<string>("LocalityCp")
                        .HasColumnType("text");

                    b.Property<int?>("LocalityDistrictCode")
                        .HasColumnType("integer");

                    b.Property<int>("LocalityInaccuracyLevel")
                        .HasColumnType("integer");

                    b.Property<double?>("LocalityLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("LocalityLongitude")
                        .HasColumnType("double precision");

                    b.Property<int?>("LocalityMunicipalityCode")
                        .HasColumnType("integer");

                    b.Property<int?>("LocalityRuian")
                        .HasColumnType("integer");

                    b.Property<int?>("LocalityRuianLevel")
                        .HasColumnType("integer");

                    b.Property<string>("LocalityStreet")
                        .HasColumnType("text");

                    b.Property<bool>("Loggia")
                        .HasColumnType("boolean");

                    b.Property<int?>("LoggiaArea")
                        .HasColumnType("integer");

                    b.Property<string>("MapyPanoramaUrl")
                        .HasColumnType("text");

                    b.Property<string>("MatterportUrl")
                        .HasColumnType("text");

                    b.Property<bool>("Mortgage")
                        .HasColumnType("boolean");

                    b.Property<double?>("MortgagePercent")
                        .HasColumnType("double precision");

                    b.Property<int?>("NoliveTotalArea")
                        .HasColumnType("integer");

                    b.Property<int?>("NumOwners")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectAge")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectKind")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectLocation")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectType")
                        .HasColumnType("integer");

                    b.Property<int?>("OfficesArea")
                        .HasColumnType("integer");

                    b.Property<int?>("Ownership")
                        .HasColumnType("integer");

                    b.Property<int?>("Panorama")
                        .HasColumnType("integer");

                    b.Property<int?>("Parking")
                        .HasColumnType("integer");

                    b.Property<bool>("ParkingLots")
                        .HasColumnType("boolean");

                    b.Property<double?>("Personal")
                        .HasColumnType("double precision");

                    b.Property<int?>("PhaseDistribution")
                        .HasColumnType("integer");

                    b.Property<double?>("PriceAuctionPrincipal")
                        .HasColumnType("double precision");

                    b.Property<double?>("PriceExpertReport")
                        .HasColumnType("double precision");

                    b.Property<double?>("PriceMinimumBid")
                        .HasColumnType("double precision");

                    b.Property<int?>("ProductionArea")
                        .HasColumnType("integer");

                    b.Property<int?>("Protection")
                        .HasColumnType("integer");

                    b.Property<DateOnly?>("ReadyDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("RealtyAgencyId")
                        .HasColumnType("uuid");

                    b.Property<int?>("ReconstructionYear")
                        .HasColumnType("integer");

                    b.Property<double?>("RefundableDeposit")
                        .HasColumnType("double precision");

                    b.PrimitiveCollection<int[]>("RoadType")
                        .HasColumnType("integer[]");

                    b.Property<DateOnly?>("SaleDate")
                        .HasColumnType("date");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .HasColumnType("tsvector");

                    b.Property<Guid?>("SellerId")
                        .HasColumnType("uuid");

                    b.Property<string>("SellerRkId")
                        .HasColumnType("text");

                    b.Property<int?>("ShareCommonAreaDenominator")
                        .HasColumnType("integer");

                    b.Property<int?>("ShareCommonAreaNumerator")
                        .HasColumnType("integer");

                    b.Property<int?>("ShareDenominator")
                        .HasColumnType("integer");

                    b.Property<int?>("ShareNumerator")
                        .HasColumnType("integer");

                    b.Property<int?>("ShopArea")
                        .HasColumnType("integer");

                    b.Property<bool>("SolarPanels")
                        .HasColumnType("boolean");

                    b.Property<double?>("SporPercent")
                        .HasColumnType("double precision");

                    b.Property<string>("Steps")
                        .HasColumnType("text");

                    b.Property<int?>("StoreArea")
                        .HasColumnType("integer");

                    b.Property<int?>("SurroundingsType")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Telecommunication")
                        .HasColumnType("integer[]");

                    b.Property<bool>("TenantNotPayCommission")
                        .HasColumnType("boolean");

                    b.Property<bool>("Terrace")
                        .HasColumnType("boolean");

                    b.Property<int?>("TerraceArea")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<int[]>("Transport")
                        .HasColumnType("integer[]");

                    b.Property<int?>("UndergroundFloors")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UsableArea")
                        .HasColumnType("integer");

                    b.Property<bool>("UserStatus")
                        .HasColumnType("boolean");

                    b.PrimitiveCollection<int[]>("Water")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("WaterHeatSource")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<int[]>("WellType")
                        .HasColumnType("integer[]");

                    b.Property<int?>("WorkshopArea")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LocalityDistrictCode");

                    b.HasIndex("LocalityMunicipalityCode");

                    b.HasIndex("RealtyAgencyId");

                    b.HasIndex("SellerId");

                    b.HasIndex("SellerRkId");

                    b.HasIndex("AdvertType", "CreatedAt")
                        .IsDescending(false, true);

                    b.HasIndex("RealtyAgencyId", "AdvertRkId")
                        .IsUnique()
                        .HasFilter("\"AdvertRkId\" IS NOT NULL AND \"RealtyAgencyId\" IS NOT NULL");

                    b.HasIndex("AdvertType", "LocalityCity", "AdvertPrice");

                    b.ToTable("SrealityAdverts");
                });

            modelBuilder.Entity("Server.Features.SRealty.Photo.Entity.SrealityAdvertPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<int?>("RoomType")
                        .HasColumnType("integer");

                    b.Property<Guid>("SrealityAdvertId")
                        .HasColumnType("uuid");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SrealityAdvertId", "Order")
                        .IsUnique();

                    b.ToTable("SrealityAdvertPhoto");
                });

            modelBuilder.Entity("Server.Features.User.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Server.Features.User.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Server.Features.User.RefreshTokenEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByHash")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Server.Features.User.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Server.Features.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Server.Features.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Server.Features.User.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Features.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Server.Features.User.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Server.Features.RealtyAgent.Entity.RealtyAgentEntity", b =>
                {
                    b.HasOne("Server.Features.RealtyAgency.Entity.RealtyAgencyEntity", "RealtyAgency")
                        .WithMany("Agents")
                        .HasForeignKey("RealtyAgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Features.User.ApplicationUser", "User")
                        .WithOne("RealtyAgent")
                        .HasForeignKey("Server.Features.RealtyAgent.Entity.RealtyAgentEntity", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RealtyAgency");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Features.Ruian.Entity.RuianDistrictEntity", b =>
                {
                    b.HasOne("Server.Features.Ruian.Entity.RuianRegionEntity", "Region")
                        .WithMany("Districts")
                        .HasForeignKey("RegionCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("Server.Features.Ruian.Entity.RuianMunicipalityEntity", b =>
                {
                    b.HasOne("Server.Features.Ruian.Entity.RuianDistrictEntity", "District")
                        .WithMany("Municipalities")
                        .HasForeignKey("DistrictCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Server.Features.SRealty.Advert.Entity.SrealityAdvertEntity", b =>
                {
                    b.HasOne("Server.Features.Ruian.Entity.RuianDistrictEntity", "LocalityDistrict")
                        .WithMany()
                        .HasForeignKey("LocalityDistrictCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Features.Ruian.Entity.RuianMunicipalityEntity", "LocalityMunicipality")
                        .WithMany()
                        .HasForeignKey("LocalityMunicipalityCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Features.RealtyAgency.Entity.RealtyAgencyEntity", "Agency")
                        .WithMany()
                        .HasForeignKey("RealtyAgencyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Server.Features.RealtyAgent.Entity.RealtyAgentEntity", "Seller")
                        .WithMany("SRealtyProperties")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Agency");

                    b.Navigation("LocalityDistrict");

                    b.Navigation("LocalityMunicipality");

                    b.Navigation("Seller");
                });

            modelBuilder.Entity("Server.Features.SRealty.Photo.Entity.SrealityAdvertPhoto", b =>
                {
                    b.HasOne("Server.Features.SRealty.Advert.Entity.SrealityAdvertEntity", "Advert")
                        .WithMany("Photos")
                        .HasForeignKey("SrealityAdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Server.Features.User.RefreshTokenEntity", b =>
                {
                    b.HasOne("Server.Features.User.ApplicationUser", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Server.Features.RealtyAgency.Entity.RealtyAgencyEntity", b =>
                {
                    b.Navigation("Agents");
                });

            modelBuilder.Entity("Server.Features.RealtyAgent.Entity.RealtyAgentEntity", b =>
                {
                    b.Navigation("SRealtyProperties");
                });

            modelBuilder.Entity("Server.Features.Ruian.Entity.RuianDistrictEntity", b =>
                {
                    b.Navigation("Municipalities");
                });

            modelBuilder.Entity("Server.Features.Ruian.Entity.RuianRegionEntity", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Server.Features.SRealty.Advert.Entity.SrealityAdvertEntity", b =>
                {
                    b.Navigation("Photos");
                });

            modelBuilder.Entity("Server.Features.User.ApplicationUser", b =>
                {
                    b.Navigation("RealtyAgent");

                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
